name: Images

on:
  pull_request:
    branches: develop
    paths: docker/**

env:
  REGISTRY: ghcr.io/bython-talk

jobs:
  build-base-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/bython-base
          tags: |
              type=raw,value=latest,enable=true

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: docker/
          push: true
          file: docker/base.dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  build-derivate-containers:
    needs: [build-base-container]
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        container_kind: [ci, dev]

    name: Build ${{ matrix.container_kind }} Image

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/bython-${{ matrix.container_kind }}
          tags: |
            type=raw,value=latest,enable=true

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          file: docker/${{ matrix.container_kind }}.dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}