name: Lint

on:
  push:
    branches:
    - main
    - develop

  pull_request:
    branches:
    - main
    - develop
jobs:
  lint:
    runs-on: ubuntu-22.04
    permissions:
      packages: read
    container:
      image: ghcr.io/bython-talk/devcontainer:main
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.DOCKER_CONTAINER_REGISTRY_TOKEN }}

    steps:
    - uses: actions/checkout@v3

    - name: Lint
      run: |
        cmake -D FORMAT_COMMAND=clang-format -P cmake/lint.cmake

    - name: Spell check
      if: false
      run: pip3 install codespell && cmake -P cmake/spell.cmake